[project]
name = "dem"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "duckdb>=1.5.6",
    "numpy>=2.5.3",
    "openpyxl>=3.1.5",
    "osmium>=4.3.1",
    "pillow>=12.3.0",
    "pyarrow>=25.0.1",
    "pyproj>=3.8.0",
    "pyshp>=3.1.6",
    "rasterio>=1.5.1",
    "scipy>=1.18.1",
    "shapely>=2.1.2",
    "tqdm>=4.70.1",
]
